
datadump.location: 
    author: "D:/Project/test-authors.txt"
    works: "D:/Project/test-works.txt"

spring:
  main:  
    allow-circular-references: true
  data:
    cassandra:
      keyspace-name: main
      username: <username>
      password: <password>
      schema-action: recreate
      request:
        timeout: 30s
      connection:
        connect-timeout: 30s
        init-query-timeout: 30s 
   
     

datastax.astra:
    secure-connect-bundle: secure-connect.zip

astra.db:
    id: fe404251-e54e-4f24-b6e7-c9adb3267a2e-1 
    region: us-east1
    keyspace: main
    application.token: <token>